### PR TITLE
fixes for löve 11.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by airstruck** [comment]
Did Love really jump from major version 0 to major version 11? Haven't looked at it in a while...

**Comment by fendrin** [comment]
Yes, the Löve version jumped from 0.10.2 to 11.0 with the latest release.
Although the release happened on April the First the change persists.

But I am skeptical about translating color values from range 0-255 into 0-1.
This solution either forces the user to use the old range in all of her project or to handle 2 different color formats.

**Comment by ghost** [comment]
@airstruck Yes, they changed the version to 11.0, see `VERSION_MAJOR` here:

https://bitbucket.org/rude/love/src/a95b5df234f888dcf751f3fb3a39783a7bb67b5f/src/common/version.h?at=default&fileviewer=file-view-default

The color range change is documented here as `Changed all color values to be in the range 0-1, rather than 0-255.`:

https://love2d.org/wiki/11.0

**Comment by tst2005** [comment]
Hello guys,

I'm thinking about how to make a wrapper for compat.
* The 0 value stay 0 in love all versions
* The 0.xx values can detected with
```lua
if n % 1 == 0` then love11=false end
```
* For values > 1
```lua
if n > 1 then love11=false end
```
* The only **true problem** is the `1` value. We are not able to detect the difference between the old value like 1/255 and the new 1.0 like 255/255.

It remember me the worst API change ever made on Love : [love.timer.sleep](https://love2d.org/wiki/love.timer.sleep) before/after 0.8.0

**Comment by fendrin** [comment]
I don't think luigi should translate color values,
with maybe the exception of those found in the example files.

**Comment by airstruck** [comment]
@fendrin I'm torn on this one... SDL uses 0-255, so if Luigi moves to 0-1, it'll shift the problems you describe over to the SDL side. Luigi also works with older Love versions, so it'll also shift the problems back onto those versions if anyone's using them.

@tst2005 if only Lua were strongly typed ;)

I'm just gonna merge this for now, thanks @poke1024. Might be open to a 0-1 patch later, as long as it covers the SDL side. Or possibly something clever like choosing behavior based on Love version or user preference?

**Pull request merged**
