### PR TITLE
Remove explicit checks for lgui and rgui

### PR DESCRIPTION
**Pull request by rm-code**
Became redundant with 01f958fb6c938f37ff284100f5b13be4f927b71d.

### CODE REVIEW

**Comment by airstruck** [comment]
Did you test this? I don't think that commit should have made this redundant...

**Comment by rm-code** [comment]
Yes I tested it. I think they are no longer needed now that you automatically check for lgui and rgui?

**Comment by rm-code** [comment]
Hold on.

**Comment by rm-code** [comment]
Argh ... my bad ... Sorry for the noise! 

(Let's pretend this never happened :dizzy_face:)

**Comment by airstruck** [comment]
Hahah it's ok, probably my fault for writing confusing code ;)

**Comment by rm-code** [comment]
Hehe well when I tested the PR I only tested the line jumping functionality and that one still had the checks for lgui and rgui :D

Btw I want to implement luigi into [LoGiVi](https://github.com/rm-code/logivi). Would you mind if I opened "issues" for questions or is there a forum post I can turn to?

**Comment by airstruck** [comment]
Yes, please open issues with any questions! Also if you have any specific requests that would help with your project, please open issues for those too.

**Comment by rm-code** [comment]
Perfect :+1:

**Pull request closed without merging**
